import React, { useState } from 'react';
import JSZip from 'jszip';
import { BsavePackage, createVgaPaletteFile } from '../utils/bsave';
import { generateQBasicLoaderCode, generateQBasicSaverCode } from '../utils/codeGenerators';
import { RgbColor, ScreenModeDef } from '../types/qbasic';
import { Download, Archive, FileText, Image, Check, Sparkles } from 'lucide-react';

interface DownloadToolbarProps {
  bsavePkg: BsavePackage | null;
  screenMode: ScreenModeDef;
  palette: RgbColor[];
  isCustomPalette: boolean;
  outputImageData: ImageData | null;
}

export const DownloadToolbar: React.FC<DownloadToolbarProps> = ({
  bsavePkg,
  screenMode,
  palette,
  isCustomPalette,
  outputImageData,
}) => {
  const [downloadingZip, setDownloadingZip] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);

  if (!bsavePkg) return null;

  const triggerDownload = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadSuccess(filename);
    setTimeout(() => setDownloadSuccess(null), 2500);
  };

  const handleDownloadBsv = () => {
    const blob = new Blob([bsavePkg.fileBytes as unknown as BlobPart], { type: 'application/octet-stream' });
    triggerDownload(blob, bsavePkg.filename);
  };

  const handleDownloadBas = () => {
    const code = generateQBasicLoaderCode(screenMode, bsavePkg.filename, palette, isCustomPalette);
    const blob = new Blob([code], { type: 'text/plain;charset=utf-8' });
    triggerDownload(blob, 'LOADER.BAS');
  };

  const handleDownloadPal = () => {
    const palBytes = createVgaPaletteFile(palette);
    const blob = new Blob([palBytes as unknown as BlobPart], { type: 'application/octet-stream' });
    const palName = bsavePkg.filename.replace('.BSV', '.PAL');
    triggerDownload(blob, palName);
  };

  const handleDownloadPng = () => {
    if (!outputImageData) return;
    const canvas = document.createElement('canvas');
    canvas.width = outputImageData.width;
    canvas.height = outputImageData.height;
    const ctx = canvas.getContext('2d')!;
    ctx.putImageData(outputImageData, 0, 0);

    canvas.toBlob((blob) => {
      if (blob) {
        triggerDownload(blob, `${bsavePkg.filename.replace('.BSV', '')}_PREVIEW.PNG`);
      }
    });
  };

  const handleDownloadZipBundle = async () => {
    setDownloadingZip(true);
    try {
      const zip = new JSZip();

      // 1. Add .BSV file
      zip.file(bsavePkg.filename, bsavePkg.fileBytes);

      // 2. Add LOADER.BAS
      const loaderCode = generateQBasicLoaderCode(screenMode, bsavePkg.filename, palette, isCustomPalette);
      zip.file('LOADER.BAS', loaderCode);

      // 3. Add SAVER.BAS
      const saverCode = generateQBasicSaverCode(screenMode, bsavePkg.filename);
      zip.file('SAVER.BAS', saverCode);

      // 4. Add .PAL file if 8-bit or custom
      if (screenMode.bitDepth === '8-bit') {
        const palBytes = createVgaPaletteFile(palette);
        zip.file(bsavePkg.filename.replace('.BSV', '.PAL'), palBytes);
      }

      // 5. Add README.TXT with DOS instructions
      const readme = `======================================================================
QBASIC BSAVE PROJECT BUNDLE
Generated by QBasic BSAVE Converter
======================================================================

FILES INCLUDED:
1. ${bsavePkg.filename} - Authentic binary BSAVE file with 7-byte header
   - Segment: ${bsavePkg.header.segmentHex}
   - Offset:  ${bsavePkg.header.offsetHex}
   - Length:  ${bsavePkg.header.payloadLength} bytes
   - Mode:    ${screenMode.name}

2. LOADER.BAS - Ready-to-run QBasic program to display this image
3. SAVER.BAS  - Example QBasic code showing how to capture/save images
4. README.TXT - This help guide

HOW TO RUN IN DOSBOX:
1. Copy ${bsavePkg.filename} and LOADER.BAS to your DOSBox mount folder (e.g. C:\\GAMES).
2. Start DOSBox:
     mount c c:\\games
     c:
3. Start QBasic:
     qbasic /run LOADER.BAS
4. The image will load instantly into video memory!
======================================================================`;
      zip.file('README.TXT', readme);

      // Generate zip and download
      const content = await zip.generateAsync({ type: 'blob' });
      triggerDownload(content, `${bsavePkg.filename.replace('.BSV', '')}_QBASIC_BUNDLE.ZIP`);
    } catch (e) {
      console.error('Failed to generate ZIP', e);
    } finally {
      setDownloadingZip(false);
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 shadow-xl">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center space-x-2">
          <Download className="w-4 h-4 text-emerald-400" />
          <span className="text-xs font-mono font-bold text-white uppercase tracking-wider">
            Export &amp; Downloads
          </span>
          {downloadSuccess && (
            <span className="text-xs font-mono text-emerald-400 flex items-center gap-1 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
              <Check className="w-3.5 h-3.5" />
              <span>Saved {downloadSuccess}!</span>
            </span>
          )}
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* Download BSV Binary */}
          <button
            onClick={handleDownloadBsv}
            className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-mono font-semibold flex items-center gap-1.5 transition-colors shadow-sm"
            title="Download authentic binary BSAVE file with 7-byte header"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download {bsavePkg.filename}</span>
          </button>

          {/* Download LOADER.BAS */}
          <button
            onClick={handleDownloadBas}
            className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-mono font-semibold flex items-center gap-1.5 transition-colors shadow-sm"
            title="Download copy-pasteable QBasic LOADER.BAS"
          >
            <FileText className="w-3.5 h-3.5" />
            <span>LOADER.BAS</span>
          </button>

          {/* Download PAL Palette if 8-bit */}
          {screenMode.bitDepth === '8-bit' && (
            <button
              onClick={handleDownloadPal}
              className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-mono font-medium flex items-center gap-1.5 transition-colors border border-slate-700"
              title="Download VGA 256-color DAC Palette file (.PAL)"
            >
              <span>.PAL (768 B)</span>
            </button>
          )}

          {/* Download PNG Preview */}
          <button
            onClick={handleDownloadPng}
            className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-mono font-medium flex items-center gap-1.5 transition-colors border border-slate-700"
            title="Download PNG preview of dithered image"
          >
            <Image className="w-3.5 h-3.5" />
            <span>PNG</span>
          </button>

          {/* Download All as ZIP */}
          <button
            onClick={handleDownloadZipBundle}
            disabled={downloadingZip}
            className="px-3.5 py-1.5 bg-gradient-to-r from-amber-600 to-amber-500 hover:from-amber-500 hover:to-amber-400 text-white rounded-lg text-xs font-mono font-bold flex items-center gap-1.5 transition-all shadow-md"
            title="Download full project bundle with BSV, BAS scripts, and README in one ZIP"
          >
            <Archive className="w-3.5 h-3.5" />
            <span>{downloadingZip ? 'Creating ZIP...' : 'Full Project (.ZIP)'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
